### ISSUE TITLE
Add support for multiple elevators

### ISSUE THREAD

**Issue by jacksonrayhamilton** [caleb531/elevator#1]
Currently this just assumes 1 elevator. But many buildings are outfitted with multiple elevators. Can't an elevator pick up the slack for another, improving efficiency?

**Comment by caleb531** [comment]
Yes, coordinating multiple elevators can probably improve efficiency. However, that is beyond the requirements of the school assignment for which this algorithm was created. Therefore, it is not something I intend to implement at this point in time.
