### ISSUE TITLE
Add support for elevator capacity

### ISSUE THREAD

**Issue by jacksonrayhamilton** [caleb531/elevator#2]
In times of emergency, elevators provide an efficient means of evacuating building residents and delivering firefighters to high floors.

> China . . . require[s] any building taller than 24 meters (defined as high-rise buildings) to have a minimum number of firefighter elevators based on the floor area . . .

> The benefits of using elevators are so obvious that the building codes are changing rapidly and most tall buildings are being outfitted with elevators for egress and access even before the codes and standards can be changed. . . .

> Petronas Towers in Kuala Lumpur, Malaysia, reduced their total evacuation time from 2 hr to 20 min by incorporating elevators . . .

[Source](http://www.csemag.com/single-article/using-elevators-in-fires/7a08ea465a989ddbf13459632d52d75a.html)

In these times, it is likely an elevator will reach capacity. This program could *saves lives* if it could efficiently manage sets of passengers in larger sets of would-be passengers on arbitrary floors.

**Comment by caleb531** [comment]
This algorithm is not concerned with the number of passengers on the elevator at any given instant, as that goes beyond the requirements of the assignment for which this algorithm was created. Therefore, I do not intend to implement this feature.
